### ISSUE TITLE
Verify whether or not develop branch is broken

### ISSUE THREAD

**Issue by f4ngy** [FOSSRIT/Sash#15]
When I spoke with DAWacker initially we discovered that the develop branch wasn't working correctly (issues when being built) and he suggested that it was due to him using version 3 of gtk instead of version 2 in the setup.py file

We need to verify if this is still occurring and verify why it's happening.

**Comment by LinkSlayer64** [comment]
The develop branch builds and runs properly, verified on an actual XO.
