### ISSUE TITLE
Make Sash run as a proper XO Activity

### ISSUE THREAD

**Issue by f4ngy** [FOSSRIT/Sash#18]
This will also allow implementation of the universal toolbar

**Comment by LinkSlayer64** [comment]
So, as I've tried to analyze the code, I noticed this project does not follow most other activites basic setups of using "activity" imported from sash, which would give full access to the natural Sugar toolbar.
I've been working on trying to convert over, but I keep getting issues I need to debug

**Comment by LinkSlayer64** [comment]
http://u104.guest.isc.org/make-your-own-sugar-activities/making-new-style-toolbars/
Sample code

**Comment by rxg1565** [comment]
http://git.sugarlabs.org/memorize/mainline/blobs/master/activity.py
Moar sample code

**Comment by rxg1565** [comment]
http://wiki.laptop.org/go/Sugar.activity.activity
stuff aboot activity.activity

**Comment by f4ngy** [comment]
Hi guys, still working on this, I'll make sure to have it done by tomorrow though so that we can test it before the Tuesday playtest

**Comment by f4ngy** [comment]
I think the reason they made it so that Sash.py doesn't use sugar activity is so that it can be run on a computer easily without having to use an XO simulator, but like Zach has said this results in us being unable to access features from the activity class.  I think I can change Sash.py to use activity but I might need to figure out how to XO simulator works so that I can run it. I don't think its possible for me to run it as a sugar activity on my vm out of the box? I need to be able to send the sash init an activity.

**Comment by LinkSlayer64** [comment]
Fangy - if you installed sugar and sugar-emulator on your vm, you can build the Sash.xo file, then in the folder the xo file is located in, run sugar-install-bundle "sash.xo filename here" then you can launch sugar-emulator and it will have sash installed to test

**Comment by LinkSlayer64** [comment]
commit 9f93636c2e8b8e510c7e723eee38e8f778a3fc7c
