### ISSUE TITLE
Research how Open Badges work

### ISSUE THREAD

**Issue by f4ngy** [FOSSRIT/Sash#20]
we can look at how fedora badges work https://badges.fedoraproject.org/

also 

http://billymeinke.wordpress.com/2012/05/24/open-badges-want-to-make-your-own-badges-by-hand-heres-how/
https://wiki.mozilla.org/Badges/FAQs
https://wiki.mozilla.org/Badges

**Comment by f4ngy** [comment]
https://github.com/mozilla/openbadges/wiki/Issuer-API

There's an issuer API that handles baking and all that, but it seems to be used with websites.  I'm not sure if we'd be able to get it work with a Sugar application.

Another issue I'm seeing is that the json holds the URL to the badge image, whereas the badge images we're using aren't going to be hosted online anywhere, they're simply on the machine.

**Comment by f4ngy** [comment]
Also I did the manual badge-making and it worked fine.  You just have to write the json, host it somewhere, use their baking service to create a png and then upload that png to your backpack. I don't think that workflow will work for our project though. I'm going to ask in the IRC channel about the Issuer API.

**Comment by JoePrezioso** [comment]
I'm not sure what to do about the first issue. 

As for the second...maybe look into hosting our badges online? 

----- Original Message -----

**Comment by f4ngy** [comment]
<Fangy> Hello, does anyone know if it is possible to use the Issuer API with a desktop application? (written in Python)
<cmcavoy> Fangy, it's essentially a web api, so if you used a web window in your python app, then yes.
<Fangy> Okay, thank you
