### ISSUE TITLE
Make a lesson plan!

### ISSUE THREAD

**Issue by f4ngy** [FOSSRIT/Sash#24]
We need to make a lesson plan?

**Comment by JoePrezioso** [comment]
As I understand it, we need to explain what the benefit of badges will be to the educational environment.

**Comment by f4ngy** [comment]
Do we know when this is due?

**Comment by JoePrezioso** [comment]
I am uncertain. However, I am finally back in Rochester -- albeit, after a very long trip -- So, I'll be able to work on whatever we need at the moment. 

----- Original Message -----
