### ISSUE TITLE
Determine what other teams have projects we can add badges to

### ISSUE THREAD

**Issue by f4ngy** [FOSSRIT/Sash#30]
This is not committing to adding badges yet, this is just investigating what other projects would be interested in having badges added

**Comment by rxg1565** [comment]
I meant to close this last week. Oops.

So far we have two teams expressing interest, but none seem to have time to implement them at this point

Fortune Hunter:
https://github.com/FOSSRIT/fortunehunter

Blocku:
https://github.com/FOSSRIT/blocku

Fractionauts (name pending)
https://github.com/chrisknepper/xo-fractions-game
