### ISSUE TITLE
Attend Mozilla conference call

### ISSUE THREAD

**Issue by f4ngy** [FOSSRIT/Sash#32]
Dial in:
Conference Number: 1-800-503-2899  
Secondary Conference Number: +1 303-248-0817  
7-Digit Access Code: 5435555#

Wednesday 11/13 12pm EST

Everyone is assigned to this!

@LinkSlayer64 @rxg1565 @edwfoss @ArcticSphinx

**Comment by JoePrezioso** [comment]
When is it?

**Comment by f4ngy** [comment]
We need to talk to @decause to find out the details.

edit: Actually, this is what is linked to on their website https://openbadges.etherpad.mozilla.org/openbadges-community-2 under "Community Call"

Their next meeting is this Wednesday at noon. The phone number is listed on that site and lines are muted by default.
