### ISSUE TITLE
Research hosting the badge images

### ISSUE THREAD

**Issue by f4ngy** [FOSSRIT/Sash#34]
@ArcticSphinx and @edwfoss will be working on this as well.

-We should check out the Sugar IRC and ask them about image hosting for Sugar-related things

-If Sugar hosting isn't possible, look into some kind of hosting service we could use to have the sash application push images to

**Comment by JoePrezioso** [comment]
Found some sites where we could host images

http://postimage.org/  

Pros: 
-supports PNGs up to 5 MB
-Seems simple

Cons:
-Requires an account

Photobucket may also be an option, though it also requires an account.

http://www.freeimagehosting.net/ - Does not require an account (allegedly). Supports up to 3MB per image

**Comment by f4ngy** [comment]
walterbender: Fangy: you want to upload files from a Sugar app to somewhere?

Fangy: Our application won't be storing the images, other Sugar games will have the images and we get them from those and need to upload them online and then send that URL to Mozilla Open Badges
Fangy: walterbender- yup!

walterbender: Fangy: we don't really have any specific host for that sort of thing
walterbender: Fangy: we have places for secure upload, but not for random app upload.
walterbender: maybe tch__ has a suggestion?

tch__: walterbender, Fangy I am missing some context I think!

Fangy: tch__ Hi! We're working on adding Open Badges support to Sugar games, we have a library right now that lets other developers award badges in their games (by saving an image to the datastore) and then our app should take those images, upload them online, and then send their url to Mozilla Open Badges

tch__: Fangy: sounds good, so where exactly in that process are you having problems?

Fangy: Open Badges is expecting a url that links to the hosted image somewhere, but right now we just have images that games are saving on the XO's
Fangy: So we need to upload the images somewhere and we were wondering if anyone at Sugar had a recommendation

tch__: Fangy: easy solution: web service extensions. Are you tagging these images somehow?

Fangy: tch__ I'm sorry, I'm not sure what you mean by tagging.  Our team is kind of new to Python/Sugar

tch__: Fangy: I mean, are you guys using special metadata? Anything that can tell programatically that the image is a badge?

Fangy: tch__ no we're not, right now I believe the datastore keeps track of the name of the badge and info about it, and then we look for an image with a similiar name
Fangy: (the app was made by a previous group of students, we're taking it over for a few weeks)

tch__: Fangy: Alright, then that is the first problem you need to you, (a) how to "mark" these images and (b) how to query the datastore (which is the journal back-end) to get all these images... after you are done with that. You hack a quick web service extension that would upload these badges to the wherever you guys need it.
tch__: s/need to you/need to solve/
tch__: Fangy: if you get to the point where you have a python program that has the list of badges, from datastore I can help you move on to the uploading part.

Fangy: tch__, oh we do already have that.  We get the list of badges and their images and display them using this project: https://github.com/FOSSRIT/Sash
Fangy: So I guess we are just at the uploading stage

tch__: Fangy: ok,next question: do you guys want this process to be automated? or you want the user to make an explicit upload of his latest badges?

Fangy: We're going to have the user push a button that will take all of their new badges, upload them online, and then send a message to Open Badges saying they got a new badge
Fangy: tch__ ^^

tch__: Fangy: ok, where it should be uploading?

Fangy: tch__ well that was what I meant to ask originally, if Sugar Labs has some kind of hosting people can use.  But it sounds like there isn't, so we need to come up with an alternative

tch__: Fangy: I see, we don't have any file uploading service..

Fangy: tch__ if we find somewhere to host, would you be able to help us figure out how to do it programmatically?

tch__: Fangy: of course,

Fangy: tch__ okay thank you, I'll let my team know and we'll see if we can find a host that would be good

tch__: Fangy: alright, give some though so you end up providing "free uploads" service :) a web service could work fine..
tch__: Fangy: so you only accept files under controlled circumstances

Fangy: tch__ okay, will do!

tch__: Fangy: good luck!

Fangy: tch__ ty, I will be in touch (or a teammate will)

**Comment by JoePrezioso** [comment]
So, it looks like we're using a file/image hosting service.

Ticket closed.
