### ISSUE TITLE
Wrap webkit in a python container

### ISSUE THREAD

**Issue by f4ngy** [FOSSRIT/Sash#36]
Recommended by someone on the Open Badges community call, this should allow us to use the javascript issuer API without a web browser

Links from LinkSlayer64:
http://www.gnu.org/software/pythonwebkit/
http://stackoverflow.com/questions/6535075/good-documentation-tutorial-for-python-webkit

**Comment by LinkSlayer64** [comment]
http://webkitgtk.org/?page=documentation
http://webkitgtk.org/reference/webkitgtk/stable/index.html

**Comment by f4ngy** [comment]
We have the webkit python wrapper now, but are still figuring out how to use it with the issuer api.  So I guess we can close this ticket. https://github.com/FOSSRIT/Sash/issues/37 is where we are working on the issuer api integration with webkit.
