### ISSUE TITLE
Push the badge to Open Badges using the issuer API javascript

### ISSUE THREAD

**Issue by f4ngy** [FOSSRIT/Sash#37]
This will build off of the wrapped webkit.

**Comment by LinkSlayer64** [comment]
http://www.gnu.org/software/pythonwebkit/
http://stackoverflow.com/questions/6535075/good-documentation-tutorial-for-python-webkit
We would be using the GTK version

**Comment by LinkSlayer64** [comment]
Additionally, from my talk with Remy - although getting proper hosting for bad assertions would be important, it is not required - literally, as long as the site returns a "200 OK" HTTP response; i.e. a page is there, then a badge can validate.

**Comment by JoePrezioso** [comment]
Update: We have a button. Still working on functionality.

**Comment by JoePrezioso** [comment]
Update 2: We have a text field for the user's email.

**Comment by f4ngy** [comment]
https://github.com/mozilla/openbadges-specification/blob/master/Assertion/latest.md#badge-class

https://github.com/mozilla/openbadges/blob/development/docs/issuer/api.md

**Comment by f4ngy** [comment]
https://github.com/FOSSRIT/SkyTime/tree/develop/badges

Sample badges to use for the URLs

**Comment by LinkSlayer64** [comment]
There is an "example" folder in the develop branch btw - it holds the stuff for a test assertation

**Comment by LinkSlayer64** [comment]
A sample of how to do this is now available in "test.html" additional info is in the code's documentation itself. This requires that the issuer has web hosting and can also generate the badge, this also requires that the one receiving it has some sort of account, such as with Mozilla Persona
